version: "3"
services:
  mongo:
    image: mongo
    expose: 
      - 27017
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db
      
  dashboard:
    restart: unless-stopped
    image: mongo-express
    ports:
      - "8081:8081"
    links:
      - mongo

volumes:
  mongodata: