version: "3"
services:
  mongo:
    image: mongo
    expose: 
      - 27017
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db
  parse-dashboard:
    restart: unless-stopped
    image: parseplatform/parse-dashboard
    environment:
      - PARSE_DASHBOARD_SERVER_URL=http://localhost:1337/parse
      - PARSE_DASHBOARD_MASTER_KEY=62GqBlnLJKvM
      - PARSE_DASHBOARD_JAVASCRIPT_KEY=PC2WwBFjuT14Xal7a
      - PARSE_DASHBOARD_APP_ID=iou-shared-expenses
      - PARSE_DASHBOARD_APP_NAME=iou-shared-expenses
      - PARSE_DASHBOARD_USER_ID=admin
      - PARSE_DASHBOARD_USER_PASSWORD=pass
      - PORT=4040
      - PARSE_DASHBOARD_ALLOW_INSECURE_HTTP=1
    ports:
      - "4040:4040"
    links:
      - mongo


  dashboard:
    restart: unless-stopped
    image: mongo-express
    ports:
      - "8081:8081"
    links:
      - mongo

volumes:
  mongodata: