FROM node as builder

COPY ./parse-server/package.json /usr/src/app/
COPY ./parse-server/tsconfig.json /usr/src/app/
COPY ./parse-server/tslint.json /usr/src/app/
COPY ./parse-server/src/ /usr/src/app/src/
COPY ./core /usr/src/core

RUN npm install -g yarn

WORKDIR /usr/src/core

RUN yarn install
RUN yarn run build

WORKDIR /usr/src/app

RUN yarn install
RUN yarn run build

FROM parseplatform/parse-server

COPY --from=builder /usr/src/app /parse-server/cloud2